In [5]:
import pandas as pd
import numpy as np
import shutil as sh
from tqdm import tqdm

In [2]:
df = pd.read_csv(
    'E:/ML projects/gliobastoma-mgmt/Codes/Arbitrary/UPENN-GBM_data_availability.csv')
df

,ID,Structural imaging,DTI imaging,DSC imaging,Automatic Tumor Segmentation,Corrected Tumor Segmentation,Gender,Age,Overall Survival,IDH1,MGMT,KPS,Extent of Resection,Associated Baseline Scan,Associated Recurrence Scan,PsP_TP score,CaPTk Radiomic Features
0,UPENN-GBM-00001_11,available,available,available,available,available,available,available,not available,available,not available,not available,available,-,not available,not available,available
1,UPENN-GBM-00002_11,available,available,available,available,available,available,available,available,available,not available,not available,available,-,not available,not available,available
2,UPENN-GBM-00003_11,available,available,available,available,available,available,available,not available,available,not available,not available,available,-,not available,not available,available
3,UPENN-GBM-00004_11,available,available,available,available,available,available,available,not available,not available,not available,not available,available,-,not available,not available,available
4,UPENN-GBM-00005_11,available,available,available,available,available,available,available,not available,available,not available,not available,available,-,not available,not available,available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,UPENN-GBM-00626_21,available,available,available,not available,not available,available,available,not available,available,available,not available,not available,not available,-,available,not available
667,UPENN-GBM-00627_21,available,available,available,not available,not available,available,available,not available,available,not available,not available,not available,not available,-,available,not available
668,UPENN-GBM-00628_21,available,available,available,not available,not available,available,available,not available,available,not available,not available,not available,not available,-,available,not available
669,UPENN-GBM-00629_21,available,available,available,not available,not available,available,available,not available,available,available,not available,not available,not available,-,available,not available
670,UPENN-GBM-00630_21,available,available,available,not available,not available,available,available,not available,available,available,not available,not available,not available,-,available,not available

In [3]:
len(df)

671

In [4]:
df1 = pd.DataFrame({
    "id": [],
    "mgmt": [],
})
df1

Empty DataFrame
Columns: [id, mgmt]
Index: []

In [5]:
# Removing spaces in column name
df.columns = [c.replace(' ', '_') for c in df.columns]
df

,ID,Structural_imaging,DTI_imaging,DSC_imaging,Automatic_Tumor_Segmentation,Corrected_Tumor_Segmentation,Gender,Age,Overall_Survival,IDH1,MGMT,KPS,Extent_of_Resection,Associated_Baseline_Scan,Associated_Recurrence_Scan,PsP_TP_score,CaPTk_Radiomic_Features
0,UPENN-GBM-00001_11,available,available,available,available,available,available,available,not available,available,not available,not available,available,-,not available,not available,available
1,UPENN-GBM-00002_11,available,available,available,available,available,available,available,available,available,not available,not available,available,-,not available,not available,available
2,UPENN-GBM-00003_11,available,available,available,available,available,available,available,not available,available,not available,not available,available,-,not available,not available,available
3,UPENN-GBM-00004_11,available,available,available,available,available,available,available,not available,not available,not available,not available,available,-,not available,not available,available
4,UPENN-GBM-00005_11,available,available,available,available,available,available,available,not available,available,not available,not available,available,-,not available,not available,available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,UPENN-GBM-00626_21,available,available,available,not available,not available,available,available,not available,available,available,not available,not available,not available,-,available,not available
667,UPENN-GBM-00627_21,available,available,available,not available,not available,available,available,not available,available,not available,not available,not available,not available,-,available,not available
668,UPENN-GBM-00628_21,available,available,available,not available,not available,available,available,not available,available,not available,not available,not available,not available,-,available,not available
669,UPENN-GBM-00629_21,available,available,available,not available,not available,available,available,not available,available,available,not available,not available,not available,-,available,not available
670,UPENN-GBM-00630_21,available,available,available,not available,not available,available,available,not available,available,available,not available,not available,not available,-,available,not available

In [6]:
from tqdm import tqdm
for i in tqdm(range(len(df))):
    if df.MGMT[i] == "available" and (df.Automatic_Tumor_Segmentation[i] == "available" or df.Corrected_Tumor_Segmentation[i]== "available") and df.Structural_imaging[i] == "available" and df.Overall_Survival[i] =="available" :
        df2 = pd.DataFrame({'id': [df.ID[i]],
                           'mgmt': ["available"]},
                           )
        df1 = df1.append(df2)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 671/671 [00:00<00:00, 1252.73it/s]

In [7]:
len(df1)

213

In [8]:
df1.head()

                   id       mgmt
0  UPENN-GBM-00022_11  available
0  UPENN-GBM-00034_11  available
0  UPENN-GBM-00088_11  available
0  UPENN-GBM-00091_11  available
0  UPENN-GBM-00093_11  available

In [7]:
import os
# path to UPENN Dataset
path = 'E:/ML projects/gliobastoma-mgmt/'
path_modalities=path+ 'NifTI-files/'
path_structural_images=path_modalities+'images_structural/'
path_automated_seg=path_modalities+'automated_segm/'
path_automated_seg=path_modalities+'images_segm/'

In [10]:
path_structural_images

'E:/ML projects/gliobastoma-mgmt/NifTI-files/images_structural/'

In [11]:
len(os.listdir(path_structural_images))

671

In [12]:
len(os.listdir(path_automated_seg))

611

In [13]:
df1

                    id       mgmt
0   UPENN-GBM-00022_11  available
0   UPENN-GBM-00034_11  available
0   UPENN-GBM-00088_11  available
0   UPENN-GBM-00091_11  available
0   UPENN-GBM-00093_11  available
..                 ...        ...
0   UPENN-GBM-00596_11  available
0   UPENN-GBM-00597_11  available
0   UPENN-GBM-00602_11  available
0   UPENN-GBM-00604_11  available
0   UPENN-GBM-00609_11  available

[213 rows x 2 columns]

In [14]:
df3=pd.read_csv('E:/ML projects/gliobastoma-mgmt/Codes/Arbitrary/UPENN-GBM_clinical_info_v1.1.csv')
df3

,ID,Gender,Age_at_scan_years,Survival_from_surgery_days,IDH1,MGMT,KPS,GTR_over90percent,Time_since_baseline_preop,PsP_TP_score
0,UPENN-GBM-00001_11,F,52.16,Not Available,Wildtype,Not Available,Not Available,Y,0,NaN
1,UPENN-GBM-00002_11,F,61.30,291,Wildtype,Not Available,Not Available,Y,0,NaN
2,UPENN-GBM-00003_11,M,42.82,Not Available,Wildtype,Not Available,Not Available,Y,0,NaN
3,UPENN-GBM-00004_11,M,33.43,Not Available,NOS/NEC,Not Available,Not Available,Y,0,NaN
4,UPENN-GBM-00005_11,M,53.33,Not Available,Wildtype,Not Available,Not Available,Y,0,NaN
...,...,...,...,...,...,...,...,...,...,...
666,UPENN-GBM-00626_21,F,57.19,Not Available,Wildtype,Unmethylated,Not Available,Not Applicable,234,5.0
667,UPENN-GBM-00627_21,F,57.40,Not Available,Wildtype,Not Available,Not Available,Not Applicable,Not Available,4.0
668,UPENN-GBM-00628_21,M,55.09,Not Available,Wildtype,Not Available,Not Available,Not Applicable,Not Available,6.0
669,UPENN-GBM-00629_21,M,71.44,Not Available,Wildtype,Unmethylated,Not Available,Not Applicable,Not Available,6.0
670,UPENN-GBM-00630_21,M,65.47,Not Available,Wildtype,Methylated,Not Available,Not Applicable,Not Available,2.0

In [19]:
df4=pd.DataFrame({"id": [], "mgmt":[], "age":[], "gender":[], "survival":[]})
df4

Empty DataFrame
Columns: [id, mgmt, age, gender, survival]
Index: []

In [20]:
from tqdm import tqdm
arr=df1.id.to_numpy()
print("Total patients: ",len(arr))
count=0

for i in tqdm(range(len(df3))):
   
    if df3.ID[i] in arr:
        
        l="0"
        
        if df3.MGMT[i] == 'Unmethylated':
            pass
        else:
            l="1"
        # print(df3.MGMT[i])
        df5 = pd.DataFrame({'id': [df3.ID[i]],
                           'mgmt': [l],
                           'age': [df3.Age_at_scan_years[i]],
                           'gender': [df3.Gender[i]],
                           "survival": [df3.Survival_from_surgery_days[i]]
                            })
        df4= df4.append(df5)

 39%|â–ˆâ–ˆâ–ˆâ–‰      | 265/671 [00:00<00:00, 1337.66it/s]

Total patients:  213

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 671/671 [00:01<00:00, 584.22it/s]

In [21]:
len(df4)

213

In [22]:
df4.head()

                   id mgmt    age gender survival
0  UPENN-GBM-00022_11    0  53.88      F     1882
0  UPENN-GBM-00034_11    0  53.63      F      464
0  UPENN-GBM-00088_11    0  47.32      M      334
0  UPENN-GBM-00091_11    0  70.54      M      200
0  UPENN-GBM-00093_11    0  51.30      F      616

In [23]:
df4.to_csv('upenn_data.csv')

In [24]:
arr1=df4.mgmt.to_numpy()
arr1

array(['0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '1',
       '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0',
       '1', '0', '1', '1', '0', '0', '1', '0', '0', '0', '1', '0', '1',
       '0', '0', '0', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0',
       '0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0',
       '0', '0', '1', '0', '0', '0', '0', '1', '1', '0', '1', '1', '0',
       '1', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1', '0', '0',
       '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1',
       '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0',
       '0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '1', '0',
       '0', '0', '0', '1', '0', '1', '1', '0', '0', '0', '0', '0', '1',
       '1', '0', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1', '0',
       '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '1', '1', '1',
       '0', '0', '1', '0', '1', '1', '1', '1', '0', '1', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0',
       '0', '0', '1', '0', '0'], dtype=object)

In [25]:
# Counting Methylated and Unmethylated patients
countn=0
countp=0
for i in range(len(arr1)):
    if arr1[i]=='0':
        countn+=1
    else:
        countp+=1
print(countn,countp)

139 74

In [26]:
df4.to_csv('check.csv')

In [ ]:
df1.id.to_numpy()

In [8]:
df6=pd.read_csv('E:/ML projects/gliobastoma-mgmt/Codes/check.csv')
df6

     Unnamed: 0                  id  mgmt    age gender  survival
0             0  UPENN-GBM-00022_11     0  53.88      F      1882
1             0  UPENN-GBM-00034_11     0  53.63      F       464
2             0  UPENN-GBM-00088_11     0  47.32      M       334
3             0  UPENN-GBM-00091_11     0  70.54      M       200
4             0  UPENN-GBM-00093_11     0  51.30      F       616
..          ...                 ...   ...    ...    ...       ...
208           0  UPENN-GBM-00596_11     0  81.95      F        46
209           0  UPENN-GBM-00597_11     0  61.92      F       381
210           0  UPENN-GBM-00602_11     1  77.19      M       252
211           0  UPENN-GBM-00604_11     0  62.00      F       234
212           0  UPENN-GBM-00609_11     0  29.01      M       138

[213 rows x 6 columns]

In [9]:
m_neg = 'E:/ML projects/gliobastoma-mgmt/Data/MGMT_negative/'
m_pos = 'E:/ML projects/gliobastoma-mgmt/Data/MGMT_positive/'

pos = 0
neg = 0
for i in tqdm(range(len(df6))):
    path1 = path_structural_images+df6.id[i]

    if df6.mgmt[i]==0 and neg<3: # only 5 negatives
        path2= m_neg+df6.id[i]+'/'
        sh.copytree(path1,path2)
        neg+=1
    elif df6.mgmt[i]==1 and pos<3: # only 5 positives
        path2=m_pos+df6.id[i]+'/'
        sh.copytree(path1,path2)
        pos+=1

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 213/213 [00:01<00:00, 146.38it/s]

In [31]:
path1=path_structural_images+df6.id[1]
path1

'E:/ML projects/gliobastoma-mgmt/NifTI-files/images_structural/UPENN-GBM-00034_11'

In [32]:
type(df6.mgmt[0])

numpy.int64

In [ ]:
# for negative mgmt
neg_ar=os.listdir(m_neg)
for i in tqdm(range(len(neg_ar))):

In [39]:
neg_ar=os.listdir(m_neg)
if '.DS_Store' in neg_ar:
    neg_ar.remove('.DS_Store')
    print("Removed .DS_Store")
len(neg_ar)

3